### ISSUE TITLE
demande info

### ISSUE THREAD

**Issue by fastenspy** [LeoTechmaker/FollowersCounter#1]
Bonjour.

Comment désactiver API YouTube? Car quand je laisse par défaut le fichier config j'ai une erreur.
Merci

**Comment by Fardenco** [comment]
Tu peux changer la valeur sous "Maintient d'un média" par 2 ou 3 (2 = Twitter, 3 = Facebook)

**Comment by fastenspy** [comment]
Merci j'ai déjà essayé ! Ça fonctionne parfaitement avec twitter mais Facebook pas possible ! J'ai bien rentré l'ID de la page mais pour le token je ne trouve pas j'ai tout essayé.

**Comment by Fardenco** [comment]
Le token il faut le demander à Facebook
Tu peux suivre ce qui est expliqué sur cette page pour avoir un token permanent : 
https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token

Si non tu as cette vidéo ou le gars fait exactement la même chose : 
https://www.youtube.com/watch?v=FtboHvg3HtY
