### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by p0lak** [LeoTechmaker/FollowersCounter#11]
Salut alors tout d'abord merci pour ton projet.
Néanmoins je ne comprend pas du tout comment récupérer l'API sur instagram.
Aussi comment envoyer le code sur l'Arduino oO. Bon ca c'est autre chose, aussi j'aimerais savoir comment désactiver Twitter, Facebook et Youtube stp.
Merci Chris ;)

**Comment by Fardenco** [comment]
Pour récupérer la clé d'API Instagram, c'est par ici
https://www.instagram.com/developer/
Pour envoyer le programme sur l'Arduino, ça se fait de la même manière que pour n'importe quel autre programme
Tu pourras désactiver les autres réseaux une fois le compteur démarré en accédant à l'interface web à l'adresse ip/index
