### ISSUE TITLE
Impossible de trouver l'IP de son ESP8266

### ISSUE THREAD

**Issue by Startix** [LeoTechmaker/FollowersCounter#12]
Bonjour, je trouve votre projet génial et j'ai voulu le refaire sauf que j'ai rencontré quelques problèmes (qui sont surement liée à mon incompétence dans ce domaine),et j'ai réussi à les résoudre et à téléverser le code sur l'ESP sauf que quand je regarde sur le Moniteur Série pour récupérer l'IP comme expliquer "_Pour connaitre son IP, on peut se connecter à l'ESP avec un câble USB puis ouvrir la liaison série_" il me met seulement ça "_⸮⸮⸮⸮⸮⸮⸮_" et le message est jamais le même, j'en ai conclu que le programme n'était pas en bon fonctionnement, après pas mal de recherches je n'ai toujours pas trouvé et j'aimerais que quelqu’un puisse m'éclairer sur ce dis-fonctionnement, merci.

**Comment by Fardenco** [comment]
Je pense que tu n'es pas sur le bon baud rate
Vérifie que tu es bien réglé sur 115200 bauds sur le moniteur série

**Comment by Startix** [comment]
Merci beaucoup, ça a fonctionné et ça m'a affiché ça :
`18:58:31.838 -> 
18:58:31.838 -> Connecting to freebox
.

18:58:40.195 ->  ets Jan  8 2013,rst cause:4, boot mode:(1,7)
18:58:40.195 -> 
18:58:40.195 -> wdt reset`
sauf que je n'arrive toujours pas à identifier son IP, saurais tu comment faire ?
Merci que tu prennes du temps pour m'aider :D

**Comment by Fardenco** [comment]
Ce qui s'affiche indique que le contrôleur a crashé
Il faudrait que tu essaies un programme d'exemple, comme celui de l'api Facebook, pour voir ce qu'il se passe

**Comment by Startix** [comment]
J'ai donc essayer avec l'exemple de l'API de Facebook "GetFanCount" comme tu me l'as demandé et voilà ce qu'affiche le Moniteur Série :
```
Connecting Wifi: freebox
........
21:10:56.306 -> WiFi connected
21:10:56.306 -> IP address: 
21:10:56.306 -> 192.168.0.30
Failed to open config file
JSON respnse was not as expected
21:11:04.679 -> Error getting likes
```
donc là on voit bien son adresse IP local mais ensuite une erreur se produit, aurai t'il un rapport avec le crash lors de l'autre programme ?

**Comment by Fardenco** [comment]
Ça montre déjà que la connexion à ton réseau fonctionne.
Par contre ta clé d'API Facebook n'est visiblement pas bonne, mais c'est pas ça notre problème car le contrôleur crash avant même d'être connecté au réseau.
Tu utilises quelle carte ?
Est-ce que toutes tes librairies sont à jour ?

**Comment by Startix** [comment]
J'utilise la carte que LeoTechmaker a mis en description https://fr.aliexpress.com/item/Free-Shipping-1pcs-Smart-Electronics-ESP-I2E-WeMos-D1-WiFi-uno-based-ESP8266-shield-for-arduino/32728504011.html?aff_platform=link-c-tool&cpt=1540325611160&sk=eqvBmuv&aff_trace_key=75ec82eefe76401da9c027e22d0f0a4b-1540325611160-03673-eqvBmuv&terminal_id=b511a0b1cc0d460f8d17353a18c58590
et les librairies :
ArduinoJson-v5.13.2
et les autres je n'ai pas trouvé de version mais je les ai téléchargé ce matin sur ces liens
https://github.com/witnessmenow/arduino-youtube-api
https://github.com/adafruit/Adafruit_NeoPixel
https://github.com/witnessmenow/arduino-facebook-api

**Comment by Fardenco** [comment]
Est-ce que le core ESP8266 est bien à jour ?

**Comment by Startix** [comment]
J'ai la version ESP8266 v 2.4.2 et je n'ai pas trouvé une plus récente et il me semble qu'il fallait bien prendre un version différent de la v 2.4.1 donc ça devrai être bon

**Comment by Fardenco** [comment]
Ok alors c'est bizarre
Est-ce que tu pourrais réessayer en vérifiant bien que toutes les informations sont bonnes ?

**Comment by Startix** [comment]
J'ai réessayé en vérifiant bien que j'utilise les dernières version donc avec ArduinoJson-v5.13.2 , Youtube Api 1.1.0 , Adafruit_NeoPixel 1.1.6 , FaceBook Api 1.0.0 et ESP8266 2.4.2
et étrangement là il m'a donné une erreur de compilation qui est ```
exit status 1
'DynamicJsonBuffer' was not declared in this scope
```
et pourtant j'ai pas touché au code

**Comment by Startix** [comment]
Bonjour Fardenco, ça fait longtemps que j'avais fait une pose sur ce projet mais aujourd'hui j'ai repris, j'ai tout réussi à faire fonctionner et le panneau affiche bien les nombres abonnées mais j'ai un dernier problème je n’arrive pas à accéder au site pour configurer le esp j'ai essayer le http://sonIP mais ça m'a mis "Not found: /" une idée ?

**Comment by Fardenco** [comment]
Il faut ajouter /index après l'IP

**Comment by Startix** [comment]
D'accord merci beaucoup le compteur fonctionne parfaitement ! Tout mes problèmes sont résolu ! Bonne soirée
