### ISSUE TITLE
Comment configurer son code avec ses API Facebook

### ISSUE THREAD

**Issue by virgile83** [LeoTechmaker/FollowersCounter#13]
Bonjour je souhaiterais savoir comment récupérer ses API Facebook pour les rentrer dans le code et aussi une question concernant webserver.que mettre sur cette ligne

**Comment by Fardenco** [comment]
Pour Facebook, il faut aller sur la partie développeur de Facebook pour créer une application, ce qui te permettra de récupérer une clé d'API.

Pour le serveur web, tu mets ce que tu veux, c'est les identifiants qu'il faudra rentrer pour s'y connecter
