### ISSUE TITLE
Modification fichier setting

### ISSUE THREAD

**Issue by sam54700** [LeoTechmaker/FollowersCounter#15]
Bonjour 
Comment modifier le fichier setting 

Merci d’avance

**Comment by Fardenco** [comment]
Il suffit de modifier le fichier config.h

**Comment by sam54700** [comment]
Dans la version 1 il y a pas de fichier config.h je souhaiterais faire tourner le programme sans interface web

**Comment by Fardenco** [comment]
La version 1 est faite pour tourner avec un ordinateur à côté et manque de pas mal de fonctionnalités.
Si tu ne veux pas de l'interface web, tu n'as qu'à lui mettre un mot de passe impossible et ne pas l'utiliser

**Comment by sam54700** [comment]
Re 
Pourquoi j’ai Une erreur de compilation avec la librairie apifacebook pour info j’si Un Arduino Mega

**Comment by Fardenco** [comment]
Ah mais il faut utiliser le matériel indiqué dans la description, il ne suffit pas de prendre n'importe quel microcontrôleur.
Le programme est développé pour tourner sur un ESP8266, qui embarque tout ce qu'il faut pour se connecter un réseau WiFi. Ça n'est pas le cas d'un Arduino Mega.

**Comment by sam54700** [comment]
ESP-12E WeMos D1 WiFi uno based ESP8266 shield for arduino Compatible
Bonjour cette carte pourrait convenir ?

**Comment by Fardenco** [comment]
Oui, ça devrait être très bien

**Comment by sam54700** [comment]
Bonsoir 
J’ai bien reçu la carte mais quand je compile j’ai une erreur de compilation pour la carte 

Help

**Comment by sam54700** [comment]
Bonjour 
J’ai réussi à compiler et televerser 
J’ai réussi à me connecter à mon réseau j’arrive a recupere mon adresse ip 

Mais maintenant je sèche quelle est l’etape Suivante pour info sur écran j’ai rien promis des led allumées mais qui
Non aucun sens

Par avance merci

**Comment by sam54700** [comment]
Wtd Reset 
Load 0x4010f000 len 1384 room16
Tail 8
Cheksum 0x2d
Vbb28d4a3 
Lf

Kkun a t-il une explication 

D’avance Merci
