### ISSUE TITLE
Demande info sup

### ISSUE THREAD

**Issue by sam54700** [LeoTechmaker/FollowersCounter#16]
Bonjour 
J’ai réussi à compiler et televerder sans erreur j’arrive à me connecter à mon réseau 
J’arrive Également à me connecter à l’interface web et à modifier les médias.
Cependant j’ai rien au moniteur série seulement la connexion qui et ok et rien a l’afficheur même pas le logo alors que j’ai désactivé les media sauf celui de FB
Quelqu’un pourrait l’aider Svp je patine la lol

Bien à vous

**Comment by Fardenco** [comment]
Est-ce que tu es sûr que les panneaux sont bien reliés ?
Est-ce que tu es sûr que tes clés d'API sont bonnes ?

**Comment by sam54700** [comment]
Bonjour 

Concernant les panneaux normalement c’est les bons car avec la première version j’arrive au moins afficher le logo Facebook

Par contre concernant les clés api Je ne suis pas vraiment sûre j’ai intégré au code quatre clés  le Token qui fait 30 35 caractères
 Sachant que dans les médias  j’ai que Facebook d’activer je devrais avoir au moins le logo Facebook  ?

**Comment by sam54700** [comment]
Pour info dans le script c’est bien d8 qu’il faut mettre et non 8

**Comment by Fardenco** [comment]
Normalement tu ne devrais pas avoir à modifier le fichier .ino, tout ce qui doit être modifié se trouve dans le fichier Config.h
Pour ce qui est de l'API, essaie de faire une requête toi même depuis un navigateur pour voir si la réponse est bien celle que tu attends.
