### ISSUE TITLE
Plantage du Mac avez esp8266

### ISSUE THREAD

**Issue by sam54700** [LeoTechmaker/FollowersCounter#17]
Bonjour, 
Kkun aurait une réponse car mon mac reboot directement après avoir raccordé ESP8266 à vide ? 

Bien à vous

**Comment by Fardenco** [comment]
L'ESP n'est relié à rien d'autre ? C'est bizarre que ton ordinateur redémarre comme ça

**Comment by sam54700** [comment]
Apparement j’ai un problème avec le pilote usb qui plante l’ordi je désinstalle l’ensemble ce soir et vous redis mais avec esp chinois apparement faut un Pilote spécial.

Mais j’ai ce soucis depuis que j’ai installé python 2.7 je sais même pas à quoi il sert ce truc

**Comment by Fardenco** [comment]
Je ne vois pas trop de rapport, il ne me semble pas que l'installation de Python soit accompagnée de drivers
