### ISSUE TITLE
Api insta

### ISSUE THREAD

**Issue by sam54700** [LeoTechmaker/FollowersCounter#19]
On joue 

C’est quoi le certificat ssl ? 
Comment le récupérer ? 

Merci les loulous

**Comment by Fardenco** [comment]
Celui qui est inclus ne fonctionne pas ?
Si non pour le récupérer il faut ouvrir le site dans un navigateur et aller dans les informations sur le certificat en cliquant sur le cadenas vert sur la gauche de la barre d'adresse (sur Chrome en tous cas)

**Comment by sam54700** [comment]
Bonjour,

Non il ne fonctionne pas du moins je ne pense pas je suis allé sur le cadenas il y en a plein ses clefs de sécurité laquelle choisir par avance merci

**Comment by Fardenco** [comment]
Dans l'onglet détails, tu dois avoir l'empreinte numérique. C'est ça qui t'intéresse. (footprint = empreinte en français)
