### ISSUE TITLE
Demande aide sur les APIs

### ISSUE THREAD

**Issue by Alain2l** [LeoTechmaker/FollowersCounter#20]
Bonjour,

Je n'arrive pas à faire fonctionner les API FB et Insta
Pour FB visiblement il y a eu du changement depuis Aout 2018 et je ne trouve pas d'info sur le net pour créé l'APP sur developers.facebook.

Pour Insta j'ai créé le Client mais je n'arrive pas a faire fonctionner l'API.
On inscrit le Website URL d'appel cela veux dire que si on change de réseau cela ne fonctionnera plus?

Auriez vous un petit tuto pour savoir comment créé les API, quoi ajouter comme autorisation et ou trouver les bonnes infos?

Merci d'avance

**Comment by Fardenco** [comment]
Le compteur continue de fonctionner même si on change de réseau
Pour récupérer les clés, je ne sais pas trop, je l'ai fait une fois à la création du compteur il y a 2 ans, et si ça a changé je ne suis pas au courant
Ce que je sais c'est que les clés que j'ai récupérées il y a 2 ans fonctionnent toujours aujourd'hui

**Comment by Alain2l** [comment]
Merci de ton retour.

Apres une nuit de réflexion j'ai résolue FB. Merci pour ton post avec les 2 lien (post #1 )
J'avais fait une erreur sur le Token :-(

FB
Token permanent :
https://stackoverflow.com/questions/17197970/facebook-permanent-page-access-token
Vidéo tuto pour le token perma FB
https://www.youtube.com/watch?v=FtboHvg3HtY 
Ne pas oublier la modification de la ligne 153 du fichier "FacebookApi.cpp"

Pour insta je suis toujours en recherche 
Pour instagramPageId je ne le trouve pas dans www.instagram.com/developer n'y sur mon profil. C'est normal? 
Je pense que le lien ci dessus peu faire l'affaire non?
https://codeofaninja.com/tools/find-instagram-user-id
Mais je ne trouve pas le instagramAccessToken dans les info de mon Client ID crée. Ou trouver cette information.
Pourquoi il y a Smahballon dans Config.h on doit crée un compte ?

Merci pour votre aide

**Comment by Fardenco** [comment]
Pour l'id instagram, c'est exactement ça
Smahballon ? Qu'est-ce que c'est ?
Pour le site qui génère les tokens, c'est bizarre, je ne sais pas si c'est safe ou pas.
Je pense que dans le doute, ça serait quand même mieux si tu arrivais à les récupérer normalement.

**Comment by Alain2l** [comment]
Ligne 27 du fichier Config.h
// Instagram settings
// https://smashballoon.com/instagram-feed/find-instagram-user-id/
#define instagramPageId "2368412736"
#define instagramAccessToken "xxxxxxxxxxxxxx"
#define instagramSSLCertificateFootprint "b98ffcc91caa900719fc817334b4736384dd294e"

Récupérer le Token normalement, donc le récupérer dans www.instagram.com/developer ? 
Mais aurais le chemin ou la localisation pour récupérer ce token.

**Comment by Fardenco** [comment]
Au oui en fait c'est un site pour récupérer l'id d'un compte Instagram, comme celui que vous avez trouvé par vous même.
Oui, c'est bien ce que je veux dire. Mais je l'ai fait il y a longtemps, je ne me souviens plus de la procédure exacte

**Comment by Alain2l** [comment]
Bonjour,
Merci pour toute les infos.... cela fonctionne bien depuis presque 1 mois donc je vais laisser la config comme cela et si cela tombe je reviendrais pour prendre d'autre info...
Merci encore pour le travail.
