### ISSUE TITLE
ERREUR YouTube : -1

### ISSUE THREAD

**Issue by drkmm** [LeoTechmaker/FollowersCounter#27]
Bonjour !

Voici mon problème en ayant rien changé :/

18:36:26.482 -> Connecting to *SSID*
18:36:26.991 -> .
18:36:26.991 -> YouTube - Enabled : 1 - Duration : 10
18:36:26.991 -> Twitter - Enabled : 0 - Duration : 6
18:36:26.991 -> Facebook - Enabled : 0 - Duration : 4
18:36:26.991 -> Instagram - Enabled : 0 - Duration : 10
18:36:26.991 -> 
18:36:26.991 -> WiFi connected
18:36:26.991 -> IP address: 
18:36:26.991 -> 192.168.1.***
18:36:26.991 -> 
18:36:28.610 -> YouTube API call.
18:36:28.779 -> YouTube : -1

Cela m'affiche ERREUR sur le compteur et j'ai déjà tenté de changer la clé APIs de YouTube.

**Comment by Fardenco** [comment]
Les identifiants de l'API ne sont sûrement pas bons

**Comment by drkmm** [comment]
Bah je l'avais pas changé et du jour au lendemain il m'a fait ça :/
Du coup j'ai test de rafraîchir et la même.
Tu as un tuto pour être sur que j'ai récupéré la bonne clé ?
Merci d'avance

**Comment by drkmm** [comment]
Et bien écoute... J'ai voulu retester une nouvelle clé et ça a fonctionné.
Merci ^^

**Comment by vip2810** [comment]
J'ai aussi l'erreur -1 sur YouTube, j'ai vérifié plein de fois les clés
Les mêmes clés à partir de mon browser chrome fonctionnent bien

**Comment by vip2810** [comment]
Je pense que j'ai un pb de SSL, j'ai activé le débug SSL et j'ai ça 
BSSL:_connectSSL: start connection
BSSL:Connection *will* fail, no authentication method is setup
BSSL:_wait_for_handshake: failed
BSSL:Couldn't connect. Error = 'Certificate is expired or not yet valid.'
D'ou est-ce que ça pourrait venir ?

**Comment by Fardenco** [comment]
Est-ce que tu es sûr que toutes tes librairies sont à jour ?

**Comment by vip2810** [comment]
J'ai trouvé effectivement c'était le core ESP8266, j'avais installé la version 2.5.2, en installant la 2.4.2 ça à résolu le problème.

**Comment by Fardenco** [comment]
Ok super
