### ISSUE TITLE
Encore et toujours Facebook

### ISSUE THREAD

**Issue by Marks107** [LeoTechmaker/FollowersCounter#29]
Salut tout le monde,

Ancien développeur, je débute, depuis une semaine, dans le monde de l'arduino, spécifiquement pour ce projet de compteur.

J'ai réussi à quasiment tout résoudre sauf la fameuse : Failed to parse JSON
J'ai lu tous les autres topics, même plusieurs fois et je ne trouve pas de solution à mon problème.

J'ai toujours "Erreur" en récupérant les données facebook, 0 en récupérant instagram, par contre twitter aucun problème. Le but final de mon compteur étant uniquement facebook.

J'ai bien modifié le fichier FacebookApi.cpp
J'ai fait un appel via l'url à l'API Facebook : https://graph.facebook.com/v2.9/MONID?fields=fan_count&access_token=MONTOKEN
Suite à ça j'ai bien : 
{
   "fan_count": 267,
   "id": "MONID"
}
Cependant lorsque je regarde le moniteur, il ne récupère pas l'information. Je bloque depuis deux jours... je ne voulais pas faire appel à vous mais je vous avoue que je ne sais plus quoi faire :) Si quelqu'un a une idée, je suis preneur. Merciii

EDIT : Et j'ai fait mes tests collés à la Box par rapport à la remarque sur la portée du Wifi... rien n'y fait.

**Comment by Marks107** [comment]
Quelques heures de test de plus et paf... c'est résolu. 

Il faut absolument utiliser la version 2.4.1 pour la partie gestion de carte esp8266. En effet, j'ai bien évité la version 2.4.2 (qu'il était déconseillé d'utiliser), mais j'avais utilisé la 2.5.0. Je ne recevais ni facebook ni Insta. Tout est résolu avec la 2.4.1.

**Comment by Fardenco** [comment]
Bonjour,
Tant mieux si c'est résolu.
C'est vrai que je n'ai pas été très clair dans la description : la version 2.4.1 contenait une erreur qui provoquait une fuite de mémoire, et ce bug a été corrigé dans la 2.4.2.
Mais il me semble que des choses ont changé à partir de la 2.5, qui obligeraient à revoir une partie du code. Mais comme ça fonctionne bien comme ça, je n'ai pas forcément de raison de prendre le temps de faire ça.
D'autant plus que le code en question se trouve dans les librairies que l'on utilise, donc bon
