### ISSUE TITLE
Include Start logo

### ISSUE THREAD

**Issue by danialonso** [LeoTechmaker/FollowersCounter#3]
I would love to include a start logo for when I turn on Arduino, using the entire panel of LEDs.

The logo I have created already:
```
const byte StartLogoColors[9][3] = {{0, 0, 0}, {52, 115, 34}, {80, 167, 0}, {2, 178, 142}, {0, 165, 221}, {51, 66, 181}, {114, 41, 175}, {185, 30, 183}, {189, 17, 55}};
const byte StartLogo[8][40] = 
{
  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
  {0, 1, 1, 0, 0, 2, 0, 2, 0, 0, 0, 3, 3, 3, 0, 4, 4, 4, 0, 0, 5, 0, 5, 5, 0, 5, 5, 0, 0, 0, 7, 0, 7, 0, 0, 8, 8, 8, 0, 0},
  {1, 0, 0, 1, 0, 2, 2, 0, 2, 0, 3, 0, 0, 0, 0, 0, 0, 0, 4, 0, 5, 5, 0, 5, 5, 0, 5, 0, 6, 0, 7, 7, 0, 7, 0, 0, 0, 0, 8, 0},
  {1, 1, 1, 1, 0, 2, 0, 0, 2, 0, 3, 0, 0, 0, 0, 0, 4, 4, 4, 0, 5, 0, 0, 5, 0, 0, 5, 0, 6, 0, 7, 0, 0, 7, 0, 0, 8, 8, 8, 0},
  {1, 0, 0, 0, 0, 2, 0, 0, 2, 0, 3, 0, 0, 0, 0, 4, 0, 0, 4, 0, 5, 0, 0, 5, 0, 0, 5, 0, 6, 0, 7, 0, 0, 7, 0, 8, 0, 0, 8, 0},
  {1, 0, 0, 1, 0, 2, 0, 0, 2, 0, 3, 0, 0, 0, 0, 4, 0, 0, 4, 0, 5, 0, 0, 5, 0, 0, 5, 0, 6, 0, 7, 0, 0, 7, 0, 8, 0, 0, 8, 0},
  {0, 1, 1, 0, 0, 2, 0, 0, 2, 0, 0, 3, 3, 3, 0, 0, 4, 4, 4, 0, 5, 0, 0, 5, 0, 0, 5, 0, 6, 0, 7, 0, 0, 7, 0, 0, 8, 8, 8, 0},
  {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
};
```

In **void setup()** I added a call to PrintLogoStartWithAnimation:
```
void setup()
{
  Serial.begin(115200);
  //randomSeed(analogRead(0));
  bande.begin();
  bande.setBrightness(luminosidad);
  printLogoStartWithAnimation(StartLogo, StartLogoColors);
  //printLogoWithAnimation(YtLogo, YtLogoColors);
  //print6DigitsNumberWithAnimation(0, 11, 0, 255, 255, 255, 1);
  refreshDisplay();
}
```

I have created **printLogoStartWithAnimation**:
- If **i<20**, the logo is printed correctly, but the number of followers is wrong.
- If **i<5**, the logo remains incomplete, but the number of followers is displayed correctly.
```
void printLogoStartWithAnimation(byte logo[][40], byte colors[][3])
{
  for(int i = 0; i < 20; i++)
  {
    printLogoStart(logo, colors, i);
    delay(50);
  }
}
```
I have created **printLogoStart**, with the possibility of including 40 LEDs in the array.
```
void printLogoStart(byte logo[][40], byte colors[][3], int animation = 4)
{
  for(int i = 0; i < 8; i++)
  {
    for(int j = 4 - animation; j < 6 + animation; j++)
    {
      for(int k = 0; k < 3; k++)
      {
        pannel[i][j][k] = colors[logo[i][j]][k];
      }
    }
  }
}
```

I would appreciate any help! Thank you very much!!

**Comment by Fardenco** [comment]
I'll look at this

**Comment by danialonso** [comment]
Great! Thank you very much!

**Comment by Fardenco** [comment]
The issue with your code is in the printLogoStart function.
You need to take into account the width of the logo in this for loop
`for(int j = 4 - animation; j < 6 + animation; j++)`
The values here are for a 10 pixels wide logo. Yours is 40 pixel wide, so you need to change the values to
`for(int j = 19 - animation; j < 21 + animation; j++)`
I can't test right now but I think this should work.

You'll also probably need to clear the screen before going further, if you don't want your logo to stay in background.

You can do this by looping through the pannel and setting each color from each pixel to 0

**Comment by danialonso** [comment]
Thank you very much, **your solution has worked!** The only problem is that there are 4 LEDs that stay lit by the start logo

![whatsapp image 2018-01-29 at 12 34 20 1](https://user-images.githubusercontent.com/384773/35508495-df945ea8-04f0-11e8-8adf-8f2edc58261c.jpeg)
![whatsapp image 2018-01-29 at 12 34 20](https://user-images.githubusercontent.com/384773/35508496-dfbaf040-04f0-11e8-92d1-2939ef87f2b2.jpeg)

**Comment by Fardenco** [comment]
Did you clear the pannel between the start logo and the next step ?

**Comment by Fardenco** [comment]
What do you mean by "I can't" ?
