### ISSUE TITLE
Problème instagram compteur à 000000

### ISSUE THREAD

**Issue by J3r3m38** [LeoTechmaker/FollowersCounter#30]
Bonjour, 
Je pense qu’il y a de nouveau des soucis avec Instagram mon compteur reste à 000000 même avec le compte de Léo.....
Es-qu’il serait possible de récupérer le nombre de followers avec : 
« www.instagram.com/leotechmaker/?__a=1 »

Merci d’avance

**Comment by J3r3m38** [comment]
C'est bizarre même avec ça dans le fichier de config  _#define instagramPageName "leotechmaker"_ 
mon compteur renvoi 000000 alors que sur twitter il est fonctionnel. un problème de librairie ? 
j'ai celle-ci witnessmenow/arduino-instagram-stats 1.1.2

**Comment by J3r3m38** [comment]
et sur le traceur série j'ai ça:

Instagram API call.
Instagram : 0

Twitter API call.
Twitter : 73842

**Comment by Fardenco** [comment]
Essaie de lancer l'exemple fourni avec la librairie pour voir si ça fonctionne

**Comment by J3r3m38** [comment]
je viens de trouver la solution ..... enfaîte le "gestionnaire de carte" pour l'ESP8266 était en version 2.5.2,
j'ai donc mis la version 2.4.2 et tout fonctionne correctement. Merci encore pour ton travail 👍

**Comment by Fardenco** [comment]
Ok super
