### ISSUE TITLE
Supprimer les 0 inutiles devant ? Possible ?

### ISSUE THREAD

**Issue by drkmm** [LeoTechmaker/FollowersCounter#32]
Salut Fardenco ! Voici une question que je me posais :D

Merci d'avance

**Comment by Fardenco** [comment]
Tu peux faire ça facilement en modifiant cette fonction
https://github.com/LeoTechmaker/FollowersCounter/blob/9dbd102f81ddef344562c7bb577c0e39c998e87d/Sources/Wireless_Follower_Counter.ino#L259

Il te suffit de dire que si le chiffre est un zéro et que tu n'as pas encore affiché de chiffre différent de zéro, alors tu saute l'affichage

**Comment by drkmm** [comment]
Je ne sais malheureusement pas coder...

**Comment by Startix** [comment]
SI tu souhaite retirer les 0 il te suffit de modifier le printDigit comme ceci : 
`void printDigit(char digit, int xPos, int yPos, char rValue, char gValue, char bValue, int shift = 0)
{
  int subIndex = digit / 5;
  int index = digit - subIndex * 5;

  for (int i = 0; i < 7 - abs(shift) && digit != 0; i++)
  {
    for (int j = 0; j < 4; j++)
    {
      if (xPos + j < pannelWidth && yPos + i < pannelHeight)
      {
        if (bitRead(digits[index * 7 + i + (shift > 0 ? shift : 0)], 4 * (1 - subIndex) + 3 - j))
        {
          pannel[yPos + i][xPos + j][0] = rValue;
          pannel[yPos + i][xPos + j][1] = gValue;
          pannel[yPos + i][xPos + j][2] = bValue;
        }
      }
    }
  }
}`

L’inconvénient est qu'il enlève les zéros de gauche comme ceux de droite :/

**Comment by drkmm** [comment]
Merci ça tue !

J'essayerai quand je recevrai les plaques LED car j'ai fais tombé le compteur, il est HS de ouf :D

J'essayerai ça, mais dommage qu'on puisse pas retirer uniquement ce qui est devant étant donné qu'on reçoit pas de 0 à partir de l'API

**Comment by Startix** [comment]
Je vais faire quelques recherches pour essayer d'éviter celà j'ai déjà commencé et c'est pas facile, je te ré contacterai quand j'aurai du nouveau

**Comment by Fardenco** [comment]
Ça serait mieux de mettre une condition à l'intérieur de la boucle plutôt que dans sa condition.

Pour garder les zéros de droite, Il faut juste ajouter un booléen qui reste à false tant qu'on n'a pas passé de chiffre différent de zéro, et si il est à vrai, alors tu n'enlève pas le zéro car ça signifie que tu es à droite du nombre en question, je sais pas si c'est clair

Tu peux ensuite ajouter une condition qui fait que si tu es au dernier chiffre et que c'est toujours un zéro, alors tu l'affiche quand même pour éviter d'avoir un écran vide

**Comment by Startix** [comment]
Je crois que j'ai compris l'idée oui, j'essaierai de faire ça.

**Comment by joniorozco** [comment]
Bonjour, je trouve cela très intéressant et je serais ravi de pouvoir supprimer le "0" à gauche !!  

@Startix avez-vous réussi à développer ce que Fardenco a commenté?  

Je ne sais pas si mon idée est moins complexe, j'avais prévu d'essayer comme suit: 
1 Nous recueillons la variable du nombre à afficher.  
2 Comptez les chiffres de la valeur.  
3 Avec le décompte, nous passons le nombre de chiffres à la fonction «void print6DigitsNumber».

est-ce possible?  Merci beaucoup, cordialement

**Comment by Fardenco** [comment]
Je vais essayer de regarder ça dans la semaine

**Comment by joniorozco** [comment]
Bonjour, ce serait parfait !! Je vais attendre! J'attends toujours que les documents arrivent et je ne peux pas tester .. mais je vous laisse un exemple si cela vous aide, avec cela vous obtenez le nombre de chiffres correctement:

`          int value = getMediaValue(media);
          
          Serial.print(mediaName[media]);
          Serial.print(" : ");
          Serial.println(value);
          Serial.println();


	  //Exemple de code ajouté après les lignes suivantes

          byte countDigits=0;
          while(value){
            value=value/10;
            countDigits++;
          }

          if(countDigits == 0)
          {
            countDigits=+1;
          }
          
          Serial.print("Digits : ");
          Serial.println(countDigits);
          Serial.println();`

salutations et merci

**Comment by Fardenco** [comment]
J'ai rajouté la possibilité d'enlever les zéros de gauche dans la dernière version, il suffit de changer un paramètre dans le fichier Config.h
