### ISSUE TITLE
Rajout des follows Twitch ?

### ISSUE THREAD

**Issue by drkmm** [LeoTechmaker/FollowersCounter#33]
Salut !
Tout est dans le titre, est ce que c'est envisageable ?
Même pour Leo finalement ^^

**Comment by Fardenco** [comment]
Ça n'est pas prévu mais ça ne devrait pas être trop compliqué à implémenter.
Si quelqu'un a envie de se lancer là dedans, je pourrai l'intégrer à la branche principale

**Comment by Startix** [comment]
C'est bon Fardenco j'ai rajouté le media twitch, comment je le partage ?

**Comment by drkmm** [comment]
Partage tes bouts de code ici !

En tout cas merci infiniment ! Si t'as un reseau social préféré, je le partagerai dans ma prochaine vidéo quand je parlerais du compteur si tu veux !

Merci merci !

**Comment by Startix** [comment]
OK, mais il reste 2, 3 truc à optimiser avant de le mettre

**Comment by Startix** [comment]
Voilà le programme semble bien fonctionner avec l'ajout du média Twitch j'ai utilisé la library suivante pour récupérer les stats : https://github.com/witnessmenow/arduino_twitch_api
Et le programme devrais être présent sur ce message en .zip 
Pour finir Fardenco tu peux rajouter cette modification à la branche principale comme tu l'as dit ci dessus en pensant à bien mettre le lien de cette nouvelle library à rajouter et il faut aussi récupérer un Twitch API Client ID sur https://dev.twitch.tv/build ;)
[FollowersCounter-master.zip](https://github.com/LeoTechmaker/FollowersCounter/files/3527750/FollowersCounter-master.zip)

**Comment by Fardenco** [comment]
Je vais regarder tout ça !

**Comment by Fardenco** [comment]
Et voilà, c'est intégré dans la dernière version
Merci pour le programme :)
