### ISSUE TITLE
Pb acces interface WEB

### ISSUE THREAD

**Issue by GnomeNeosam** [LeoTechmaker/FollowersCounter#36]
Bonjour,
Lorsque j'essaie de me connecter sur l'interface web j'ai le message d'erreur suivant:
Not found: /

J'ai testé avec IE, firefox et chrome.

Merci de votre aide.

**Comment by Fardenco** [comment]
Il faut ajouter /index après l'ip

**Comment by GnomeNeosam** [comment]
OK ca fonctionne. Merci Fardenco.
