### ISSUE TITLE
Ajouter des chiffres - Passer de 6 à 8 chiffres

### ISSUE THREAD

**Issue by joniorozco** [LeoTechmaker/FollowersCounter#37]
Bonjour, j’ai demandé tout le nécessaire pour mener à bien ce projet et, lorsqu’il arrive, j’aimerais adapter le code puisque j’ai commandé 6 panneaux ws2812 au lieu de 5. J’aimerais ajouter deux chiffres supplémentaires pour que le nombre total soit de 8.  Peux-tu m'aider ??  Je ne sais pas par où commencer .. merci beaucoup d'avance

**Comment by Fardenco** [comment]
Bonsoir,
En soit rien de compliqué, il faut juste remplacer quelques valeurs par ci par là..
Le truc c'est que la taille du tableau représentant le panneau doit être modifiée elle aussi.

Mais est-ce que tu as vraiment un intérêt à afficher plus de 6 chiffres au compteur ? D'autant plus que YouTube a prévu de changer son API pour rendre impossible la récupération du nombre exact d'abonnés, pour n'autoriser que les 3 chiffres les plus significatifs il me semble. Genre si tu as 123 abonnés ça t'affiche 123, mais si tu en as 12.345.678 ça ne te retournera que 12.3M.
Donc c'est un peu la galère, j'attends de voir ce que ça donne

**Comment by joniorozco** [comment]
Bonsoir, 
Je n'en savais rien, bien que Youtube apporte la modification, cela pourrait être valable pour d'autres réseaux sociaux. Cela serait résolu si nous parvenions à apporter la modification mentionnée précédemment pour compter les chiffres et transmettre la variable. Mieux vaut continuer avec ce fil:
https://github.com/LeoTechmaker/FollowersCounter/issues/32

Merci beaucoup et très bon travail.

**Comment by Fardenco** [comment]
J'ai ajouté la possibilité de rajouter des panneaux et donc des chiffres supplémentaires dans la dernière version, mais attention à la RAM, car chaque pixel en plus occupe quelques octets dans la RAM...
Si ça pose problème, il faudra passer sur un ESP32 qui en a beaucoup plus.

Pour rajouter des chiffres, il faut modifier la taille du panneau dans le code, et modifier la variable qui définit le nombre de chiffres à afficher
