### ISSUE TITLE
Facebook API call. Failed to parse JSON

### ISSUE THREAD

**Issue by Raphdeumax** [LeoTechmaker/FollowersCounter#40]
Salut @LeoTechmaker  et @Fardenco,

Merci pour d'avoir poster ce projet ! J'utilise un ESP8266 (Node MCU) et je ne parviens pas à récupérer le nombre de like sur ma page facebook. J'ai tenté d'implémenter les méhodes lié à WiFiClientSecure mais ça ne change rien, je reste au même point.

Merci d'avance.

<img width="460" alt="Sreentrouble" src="https://user-images.githubusercontent.com/31382408/65719390-02f03380-e0a6-11e9-95a5-f84c6a0da88a.PNG">
<img width="947" alt="Config" src="https://user-images.githubusercontent.com/31382408/65719405-0c799b80-e0a6-11e9-9ccd-b0938f008c40.PNG">

**Comment by Fardenco** [comment]
Il faudrait essayer de faire l'appel à la main depuis un navigateur, mais j'ai l'impression que Facebook est de plus en plus pénible sur les restrictions de son API, et qu'il faut maintenant faire une demande manuelle en montrant que tu es une entreprise ou un truc du genre pour avoir accès à certaines infos, y compris le nombre de likes de ta propre page... 
Perso je ne l'ai pas fait pour le compteur de Léo car c'est juste ridicule et qu'il n'a pas tant d'intérêt que ça à avoir Facebook sur le compteur, et dans tous les cas je trouve que c'est une mauvaise solution car c'est juste nul vis à vis des autres utilisateurs du compteur.

La meilleure solution selon moi d'un point de vue pratique serait de récupérer le nombre de likes sans passer par l'API comme expliqué ici https://github.com/LeoTechmaker/FollowersCounter/issues/8#issuecomment-532178157
L'avantage serait assez important, plus besoin de clé d'API et tout ce qui va avec, mais il faut le développer et même si ça n'est sûrement pas bien compliqué, j'avoue que je n'ai pas trop de temps à y consacrer en ce moment.

**Comment by Raphdeumax** [comment]
@Fardenco, Merci pour ta réponse ! Je vais regarder de ce côté car effectivement depuis mon navigateur ou en powershell ça marche sans problème. Le problème semble plus lié à une synchro du temps ou erreur de certificat.

Merci à toi et bonne soirée.

**Comment by Fardenco** [comment]
Ah, si ça fonctionne depuis ton navigateur alors c'est que ça ne vient pas d'une restriction de l'API
Dans ce cas c'est bizarre, car chez moi ça a toujours fonctionné jusqu'au jour où j'ai été bloqué au niveau de l'API
Quoi qu'il en soit, je pense que la solution dont je t'ai parlé dans mon post précédent serait idéale

**Comment by Raphdeumax** [comment]
@Fardenco , problème résolu en ajoutant `client.setInsecure();` dans la fontion Setup.

Bonne journée.

**Comment by Fardenco** [comment]
Je ne sais pas ce que ça implique, il me semble que l'API Facebook n'accepte pas les requêtes sans SSL donc si ça fonctionne c'est que la connexion doit bien être chiffrée
En tous cas super pour toi si ça fonctionne
