### ISSUE TITLE
Complément d'informations

### ISSUE THREAD

**Issue by DarkChimeria** [LeoTechmaker/FollowersCounter#7]
Bonjour,
Je n'ai pas trouvé d'autre endroit pour poster ma demande...

Pouvez-vous lister sur le repo les éléments nécessaires pour cette installation s'il vous plaît ?
Afin d'avoir un peu plus d'informations sur le côté hardware.

Merci beaucoup !

**Comment by dcjona** [comment]
Bonjour. Pour ma part j'ai le matériel mais sous Arduino j'ai des erreurs de compilation.  Est ce possible d'avoir un pack de libraires ? Car ceux téléchargées ne suffisent apparent pas ?

**Comment by Fardenco** [comment]
Quelles sont les erreurs affichées ?
Je suis reparti d'une installation vierge, et après avoir installé la carte et les librairies indiquées dans la description du projet, la compilation se termine sans problème

**Comment by DarkChimeria** [comment]
Merci pour ta réponse. ;)

**Comment by oizo89** [comment]
@DarkChimeria as tu réussi ?

**Comment by blackdeath1510** [comment]
bonjour tout le monde j'ai cette erreur

**Comment by Fardenco** [comment]
Le fichier config.h n'est sûrement pas dans le même dossier que le .ino

**Comment by blackdeath1510** [comment]
effectivement merci Fardenco 
 par contre maintenant j'ai un autre code erreur 


Archiving built core (caching) in: C:\Users\FAMILL~1\AppData\Local\Temp\arduino_cache_585775\core\core_esp8266_esp8266_nodemcuv2_CpuFrequency_80,VTable_flash,FlashSize_4M1M,LwIPVariant_v2mss536,Debug_Disabled,DebugLevel_None____,FlashErase_none,UploadSpeed_115200_5fe9129ede3864eb00a0f2bc92fb5581.a
Le croquis utilise 380644 octets (36%) de l'espace de stockage de programmes. Le maximum est de 1044464 octets.
Les variables globales utilisent 36476 octets (44%) de mémoire dynamique, ce qui laisse 45444 octets pour les variables locales. Le maximum est de 81920 octets.

**Comment by blackdeath1510** [comment]
j'ai commander un wemos D1 wifi quand je test il me marque cette erreur 
Arduino : 1.8.5 (Windows 7), Carte : "WeMos D1 R1, 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 921600"

Les options de compilation ont été modifiées, tout sera recompilé
xtensa-lx106-elf-gcc: error: CreateProcess: No such file or directory

exit status 1
Erreur de compilation pour la carte WeMos D1 R1

**Comment by blackdeath1510** [comment]
farenco tu utilise quel modèle ? as tu skype stp ?

**Comment by blackdeath1510** [comment]
Arduino : 1.8.5 (Windows 7), Carte : "WeMos D1 R1, 80 MHz, Flash, 4M (1M SPIFFS), v2 Lower Memory, Disabled, None, Only Sketch, 115200"

Wireless_Follower_Counter:391: error: 'answer' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(answer);

                                             ^

Wireless_Follower_Counter:393: error: expected unqualified-id before 'if'

   if (root.success()) {

   ^

exit status 1
'answer' was not declared in this scope

**Comment by Fardenco** [comment]
Est-ce que toutes les librairies nécessaires sont bien installées ?

**Comment by kurtspirit** [comment]
Salut ,
merci pour le DIY premièrement ;) . J'ai acheté le matos pour faire tout ça du coup et je me retrouve confronté à de multiples erreurs Arduino :/ 
J'ai acheté cette carte : ESP8266 ESP-12 ESP12 WeMos D1 Mini Module Wemos D1 Mini WiFi Development Board Micro USB 3.3V Based On ESP-8266EX 11 Digital Pin et je n'arrive pas à compiler le soft. En gros voici les erreurs  : 
`Arduino : 1.8.7 (Windows 10), Carte : "WeMos D1 R2 & mini, 80 MHz, 921600, 4M (3M SPIFFS)"

Wireless_Follower_Counter:46:86: error: no matching function for call to 'FacebookApi::FacebookApi(WiFiClientSecure&, const char [15], const char [15], const char [15])'

 FacebookApi facebookApi(client, facebookAccessToken, facebookAppId, facebookAppSecret);

                                                                                      ^

C:\Users\Jona\Desktop\Wireless_Follower_Counter\Wireless_Follower_Counter.ino:46:86: note: candidates are:

In file included from C:\Users\Jona\Desktop\Wireless_Follower_Counter\Wireless_Follower_Counter.ino:22:0:

C:\Users\Jona\Documents\Arduino\libraries\FacebookApi\src/FacebookApi.h:36:5: note: FacebookApi::FacebookApi(Client&, String)

     FacebookApi (Client &client, String accessToken);

     ^

C:\Users\Jona\Documents\Arduino\libraries\FacebookApi\src/FacebookApi.h:36:5: note:   candidate expects 2 arguments, 4 provided

C:\Users\Jona\Documents\Arduino\libraries\FacebookApi\src/FacebookApi.h:33:7: note: FacebookApi::FacebookApi(const FacebookApi&)

 class FacebookApi

       ^

C:\Users\Jona\Documents\Arduino\libraries\FacebookApi\src/FacebookApi.h:33:7: note:   candidate expects 1 argument, 4 provided

C:\Users\Jona\Documents\Arduino\libraries\FacebookApi\src/FacebookApi.h:33:7: note: FacebookApi::FacebookApi(FacebookApi&&)

C:\Users\Jona\Documents\Arduino\libraries\FacebookApi\src/FacebookApi.h:33:7: note:   candidate expects 1 argument, 4 provided

C:\Users\Jona\Desktop\Wireless_Follower_Counter\Wireless_Follower_Counter.ino: In function 'int getTwitterFollowerCount(String)':

Wireless_Follower_Counter:382:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

   ^

Wireless_Follower_Counter:382:21: error: expected ';' before 'jsonBuffer'

   DynamicJsonBuffer jsonBuffer;

                     ^

Wireless_Follower_Counter:383:22: error: 'jsonBuffer' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(answer);

                      ^

Wireless_Follower_Counter:385:12: error: 'class ArduinoJson::JsonObject' has no member named 'success'

   if (root.success()) {

            ^

C:\Users\Jona\Desktop\Wireless_Follower_Counter\Wireless_Follower_Counter.ino: In function 'int getInstagramFollowerCount(String, String)':

Wireless_Follower_Counter:405:3: error: 'DynamicJsonBuffer' was not declared in this scope

   DynamicJsonBuffer jsonBuffer;

   ^

Wireless_Follower_Counter:405:21: error: expected ';' before 'jsonBuffer'

   DynamicJsonBuffer jsonBuffer;

                     ^

Wireless_Follower_Counter:406:22: error: 'jsonBuffer' was not declared in this scope

   JsonObject& root = jsonBuffer.parseObject(answer);

                      ^

Wireless_Follower_Counter:408:12: error: 'class ArduinoJson::JsonObject' has no member named 'success'

   if (root.success()) {

            ^

C:\Users\Jona\Desktop\Wireless_Follower_Counter\Wireless_Follower_Counter.ino: In function 'int getFacebookFanCount(String)':

Wireless_Follower_Counter:438:22: error: 'class FacebookApi' has no member named 'getPageFanCount'

   return facebookApi.getPageFanCount(pageId);

                      ^

C:\Users\Jona\Desktop\Wireless_Follower_Counter\Wireless_Follower_Counter.ino: In lambda function:

Wireless_Follower_Counter:619:20: error: 'class ArduinoOTAClass' has no member named 'getCommand'

     if (ArduinoOTA.getCommand() == U_FLASH)

                    ^

exit status 1
no matching function for call to 'FacebookApi::FacebookApi(WiFiClientSecure&, const char [15], const char [15], const char [15])'

Ce rapport pourrait être plus détaillé avec
l'option "Afficher les résultats détaillés de la compilation"
activée dans Fichier -> Préférences.
`

Avez-vous une idée du problème ? Ça me rend dingue ;) Je ne sais pas quelle sortie connecter au LED aussi du coup, le 5V et le GND ok parfait mais la 3ème je ne trouve pas...
Merci encore, Jonathan

**Comment by dcjona** [comment]
Salut Jonathan. Ici Jonathan aussi. La troisième sortie pour tes LEDs c'est D8. Essayé de faire la mise a jour quelques postes plus haut je pense que fardenco a donné la procedure pour Facebook. Dans Arduino c'est bien le wemos d1mini ou bien loin wemos mini que tu as ?

**Comment by kurtspirit** [comment]
Salut Jonathan ;) 
J'ai acheté un Wemos D1 Mini sur Aliexpress mais je suppose que c'est encore un clone.
Impossible d'arriver à compiler et televerser le tout, c'est un truc de fou :p bon je n'y connais absolument rien en Arduino,  ça aide pas.
Si jamais vous avez une idée je suis preneur ;)
Merci encore.

**Comment by kurtspirit** [comment]
Oui Wemos d1 Mini. Mais si je décrypte l'erreur,  c'est plutôt un soucis avec le code non ?

**Comment by dcjona** [comment]
Essayé de mettre a jour le côté Arduino en 2.4.2 tu devrais avoir lolin wemos a la place de wemos. Ensuite il y a une manip décrite sur un des fils de discussion pour mettre a jour le code facebook.  Le code en lui même n'a pas d'erreur ce sont des erreurs de librairies ou autre. J'avais pareil au début. ;)

**Comment by riricky** [comment]
Bonjour, je up un peu ce thread pour demander des infos complémentaires.
Vous pourriez m'expliquer à quoi sert les pin D6 et D7 ? J'ai pas bien compris ce que ça faisait dans le code.

Merci d'avance :)

**Comment by Fardenco** [comment]
Ça sert à réinitialiser les paramètres du compteur (en cas de problème)
Si au démarrage du compteur ces deux broches sont connectées ensemble, alors tout est réinitialisé.
C'est en particulier utile pour la luminosité : si par malheur tu mets la luminosité au max alors que ton alimentation n'est pas assez puissante, alors dès que tu allumes le panneau, il essaie d'allumer les LEDs à fond, l'alim ne suit pas, tout se coupe, donc plus rien ne tire sur l'alim, donc la tension revient, donc ça redémarre, et c'est reparti
résultat impossible de modifier les paramètres pour remettre une valeur plus basse... 
À moins de relier ces deux fameuses broches ;)

**Comment by riricky** [comment]
Merci pour la réponse ;)

**Comment by vip2810** [comment]
Bonjour,
Comment fait-on pour télécharger toutes les librairies nécessaires ?

**Comment by Fardenco** [comment]
La D1 mini a un régulateur intégré, donc tu peux l'alimenter en 5V par la broche nommée... 5V ;)
