### ISSUE TITLE
Questions sur OTA et Webserver (et autres)

### ISSUE THREAD

**Issue by Braitou** [LeoTechmaker/FollowersCounter#9]
Bonjour je suis complètement nouveau dans le domaine alors pardon par avance pour ces questions : 

j'ai tout branché comme il faut mais je ne comprend pas les notions de "OTA update settings" et "Web server settings". quelqu'un pourrait-il m'éclairer ?

Questions supplémentaire il est fait mention d'une interface web pour le paramétrage, ou la trouver ??

Et pour finir, j'aimerai seulement faire tourner le compteur sur facebook et / ou sur instagram, que doit-je supprimer ? 

Merci infiniment à ceux qui me répondrons !

**Comment by Fardenco** [comment]
@Braitou OTA c'est pour mettre à jour le programme par le réseau, sans avoir à connecter le système en USB.
Le web server c'est lui qui fourni l'interface web dont tu parles.
La première chose à faire c'est de t'assurer que le compteur est bien connecté au réseau.
Il faut regarder ce qu'il envoie sur le port série.
Une fois qu'il est bien connecté au réseau, il suffit d'y accéder grâce à son adresse IP /index pour désactiver YouTube et Twitter.

**Comment by Braitou** [comment]
@Fardenco  OK super tout fonctionne !
Mon dernier problème est d'avoir accés à l'API Facebook et Instagram, y'as t-il un Tuto que je peux suivre ?

Merci par avance

**Comment by Fardenco** [comment]
@Braitou Je n'ai pas écris de tuto pour ça mais tu devrais en trouver assez facilement sur internet ou bien sur ces sites :
Facebook : https://developers.facebook.com/
Instagram : https://www.instagram.com/developer/
